# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _approximate
# more errors allowed for large words and fewer for small words
zstyle ':completion:*:approximate:*' max-errors 'reply=(  $((  ($#PREFIX+$#SUFFIX)/3  ))  )'
zstyle :compinstall filename '/home/sven/.zshrc'

autoload -Uz compinit
compinit

#autoload -Uz run-help
#unalias run-help
#alias help=run-help
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
KEYTIMEOUT=1
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
#unsetopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="custom"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

# Start or connect to tmux
# ZSH_TMUX_AUTOCONNECT="false"
# ZSH_TMUX_AUTOSTART="false"

plugins=(catimg colored-man dircycle git git-flow pass safe-paste sudo systemd z) # emacs

# Zeigt ~/.ssh/known_hosts in der Autocompletion für hosts
#zstyle -e ':completion::*:hosts' hosts 'reply=($(sed -e "/^#/d" -e "s/ .*\$//" -e "s/,/ /g" /etc/ssh_known_hosts(N) ~/.ssh/known_hosts(N) 2>/dev/null | xargs) $(grep \^Host ~/.ssh/config(N) | cut -f2 -d\  2>/dev/null | xargs))'

source $ZSH/oh-my-zsh.sh
source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh # Syntax Highlighting im Prompt.
source ~/.config/alias # Import aliases
#source ~/.config/envvars # Import environment variables

# Use incremental history with <C-p> and <C-n> too.
bindkey '^p' up-line-or-beginning-search
bindkey '^n' down-line-or-beginning-search
bindkey '^[^A' up-line-or-history
bindkey '^[^B' down-line-or-history

# # # # Vi-mode !!
# # bindkey -v
# # bindkey jk vi-cmd-mode
# # bindkey kj vi-cmd-mode
# # # allow deletes before the point where append mode was entered
# bindkey "\e[H" beginning-of-line # Home
# bindkey "\e[1;5H" beginning-of-history # Ctrl+Home
# bindkey "\e[F" end-of-line # End
# bindkey "\e[1;5F" end-of-history # Ctrl+End
# bindkey "\e[3~" delete-char
# bindkey "\e[1;5C" forward-word # Ctrl+Right
# bindkey "\e[2~" quoted-insert
# bindkey "\e[5C" forward-word
# bindkey "\eOc" emacs-forward-word
# bindkey "\e[5D" backward-word
# bindkey "\eOd" emacs-backward-word
# bindkey "\ee[C" forward-word
# bindkey "\ee[D" backward-word
# bindkey "^H" backward-delete-word
# bindkey "^?" backward-delete-char
# bindkey "^W" backward-kill-word
# # bindkey "^H" backward-delete-char      # Control-h also deletes the previous char
# bindkey "^U" backward-kill-line

# Remove mode switching delay.
KEYTIMEOUT=5

# zle-keymap-select () {
#     if [ "$TERM" = "xterm-256color" ] || [ "$TERM" = "xterm-termite" ]; then
#         if [ $KEYMAP = vicmd ]; then
#             # the command mode for vi
#             echo -ne "\e[2 q"
#         else
#             # the insert mode for vi
#             echo -ne "\e[5 q"
#         fi
#     fi
# }
# zle -N zle-keymap-select

# # Use beam shape cursor on startup.
# echo -ne '\e[5 q'

# # Use beam shape cursor for each new prompt.
# preexec() {
#     echo -ne '\e[5 q'
# }
